### ISSUE TITLE
Obselete OAuth Page resulting in error

### ISSUE THREAD

**Issue by redstonedesigner** [DiscordFederation/DiscordOAuthPhabricator#1]
**Describe the bug**

Attempts to send requests to obselete website https://discordapp.com instead of https://discord.com

**To Reproduce**
1. Install the addon
2. Configure account information
3. Attempt to link account
4. Button will grey out but not function, and an error will be displayed within the Chrome Web Console.

**Expected behavior**
Be redirected to the Discord OAuth2 Workflow.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest as of 8th September 2020

**Additional context**

**Comment by daegontaven** [comment]
This is fixed in the next version. I will release it in a few days.
